<?php

/*LICENSE INFORMATION*
 * kure is distributed under the terms of the GNU General Public License
 * (http://www.gnu.org/licenses/gpl.html).
 * kure Copyright 2007-2011 Ben Carlsson
 * 
 *-->
 * This file is part of kure.
 * 
 * kure is free software: you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License as published by the Free Software Foundation, either version
 * 3 of the License, or (at your option) any later version.
 * 
 * kure is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with kure.
 * If not, see <http://www.gnu.org/licenses/>.
 *-->
 */

class Config {

  public static $version;

  public static $adminPassword;
  public static $showAdminLink;

  public static $blogName;
  public static $blogSub;

  public static $template;

  public static $postsPerPage;

  public static $showDocDates;
  public static $showDocPageDates;

  public static $abcPosts;
  public static $abcDocs;

  public static $sort_type;
  public static $sort_order;

  __construct() {

    self::load();

  }

  __destruct() {

    self::save();

  }

  // Reads configuration from file into the Config class.
  public load() {



  }

  // Writes the current configuration to file.
  public save() {

    $options['version']          = self::$version;
    $options['adminPassword']    = self::$adminPassword;
    $options['showAdminLink']    = self::$showAdminLink;
    $options['blogName']         = self::$blogName;
    $options['blogSub']          = self::$blogSub;
    $options['template']         = self::$template;
    $options['postsPerPage']     = self::$postsPerPage;
    $options['showDocDates']     = self::$showDocDates;
    $options['showDocPageDates'] = self::$showDocPageDates;
    $options['abcPosts']         = self::$abcPosts;
    $options['abcDocs']          = self::$abcDocs;
    $options['sort_type']        = self::$sort_type;
    $options['sort_order']       = self::$sort_order;

    $write = '<?php' . "\n\n" . '// autogenerated by kure' . "\n\n";

    foreach($options as $key => $value)
      $write .= 'Config::$' . config_key($option) . ' = ' . $newvalue . ';' . "\n";

    $write .= "\n";
    return (bool)(file_put_contents($root . 'config.php', $write)); // true on success; false otherwise

  }

};

