<?php

/* LICENSE INFORMATION
 * kure is distributed under the terms of the GNU General Public License
 * (http://www.gnu.org/licenses/gpl.html).
 * kure Copyright 2007-2011 Ben Carlsson
 * 
 * This file is part of kure.
 * 
 * kure is free software: you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License as published by the Free Software Foundation, either version
 * 3 of the License, or (at your option) any later version.
 * 
 * kure is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with kure.
 * If not, see <http://www.gnu.org/licenses/>.
 */

class Config {

  private static $version;

  private static $adminPassword;
  private static $showAdminLink;

  private static $blogName;
  private static $blogSub;

  private static $template;

  private static $postsPerPage;

  private static $showDocDates;
  private static $showDocPageDates;

  private static $abcPosts;
  private static $abcDocs;

  private static $loaded = false;

  // Returns the value of property $key.
  public static function get($key) {

    if(!self::$loaded)
      self::$loaded = self::load();

    return self::$$key;

  }

  // Sets property $key to $value.
  // Returns the old value of $key.
  public static function set($key, $value) {

    $oldValue = self::$$key;

    self::$$key = $value;

    return $oldValue;

  }

  // Reads configuration from file.
  // Returns false if the config file doesn't exist; true otherwise.
  public static function load() {

    include 'config.php';

    return file_exists('config.php');

  }

  // Writes the current configuration to file.
  // Returns true on success; false otherwise.
  public static function save() {

    $options['version']          = self::$version;
    $options['adminPassword']    = self::$adminPassword;
    $options['showAdminLink']    = self::$showAdminLink;
    $options['blogName']         = self::$blogName;
    $options['blogSub']          = self::$blogSub;
    $options['template']         = self::$template;
    $options['postsPerPage']     = self::$postsPerPage;
    $options['showDocDates']     = self::$showDocDates;
    $options['showDocPageDates'] = self::$showDocPageDates;
    $options['abcPosts']         = self::$abcPosts;
    $options['abcDocs']          = self::$abcDocs;

    $write = '<?php' . "\n\n" . '// autogenerated by kure' . "\n\n";

    foreach($options as $key => $value) {

      $write .= 'Config::$' . $key . ' ';

      for($i = 0; $i < Engine::strlen_array($options); $i++) 
        $write .= ' ';

      if(is_string($value))
        $write .= '= \'' . $value . '\';' . "\n";
      elseif(is_bool($value))
        $write .= '= ' . ($value ? 'true' : 'false') . ';' . "\n";
      else
        $write .= '= ' . $value . ';' . "\n";

    }

    $write .= "\n";
    return (boolean)(file_put_contents('config.php', $write));

  }

};

